name: Test PocketFlow Agent Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    env:
      ALCHEMYST_API_KEY: ${{ secrets.ALCHEMYST_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium
          crawl4ai-setup
      - name: Run PocketFlow agent pipeline test
        run: |
          python src/test_pipeline.py 
